apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /nginx
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nginx-pvc-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: cbs-ssd
  volumeMode: Filesystem
  volumeName: nginx-pv-test
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-test
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  csi:
    driver: com.tencent.cloud.csi.cbs
    fsType: ext4
    volumeHandle: disk-xxx
  storageClassName: cbs-ssd
  volumeMode: Filesystem
