apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        livenessProbe:
          httpGet:
            path: /healthz
            port: 13043
          timeoutSeconds: 5
        image: nginx:1.7.9
        args:
          - /bin/sh
          - -c
          - ls /abc
        ports:
        - containerPort: 80
